[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg-full", "imagemagick", "python3", "pkg-config", "vips", "yt-dlp"]

[phases.install]
cmds = [
  "npm install --omit=dev --no-audit --no-fund --legacy-peer-deps"
]

[start]
cmd = "node index.js"
